[package]
name = "kprobe-rs-common"
version = "0.1.0"
edition = "2021"

[features]
aarch64 = []

[dependencies]
aya = { git = "https://github.com/aya-rs/aya", optional = true }

[lib]
path = "src/lib.rs"
